name: ruff-action
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths:
      - "scripts/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Format code
        uses: astral-sh/ruff-action@v3.4.0
        with:
          args: "format"
          src: "scripts/"
        continue-on-error: true
        

      - name: Commit format changes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Ruff formatting" || exit 0
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check code
        uses: astral-sh/ruff-action@v3.4.0
        with:
          args: "check --fix"
          src: "scripts/"
        continue-on-error: true  

      - name: Commit fixed lint errors (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add . ':!ruff_check_output.txt'
          git commit -m "Apply Ruff lint fixes" || exit 0
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
